version: '3.8'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www/html
    ports:
      - "5173:5173" 
      - "9000:9000" 
    volumes:
      - ./src:/var/www/html 
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini 
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    networks:
      - laravel_network
    depends_on:
      - mysql

  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    networks:
      - laravel_network
    depends_on:
      - app
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: local_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  mysql_data: