version: '3.8'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: buldak-app
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
      - ./docker/swagger:/var/www/html/storage/api-docs
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - buldak-network
    depends_on:
      - mysql

  web:
    image: nginx:latest
    container_name: buldak-web
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    networks:
      - buldak-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: buldak-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: local_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - buldak-network

  swagger:
    image: swaggerapi/swagger-ui
    container_name: buldak-swagger
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /api-docs/swagger_document.yaml
      VALIDATOR_URL: "none"
    volumes:
      - ./docker/swagger:/api-docs
    depends_on:
      - app
    networks:
      - buldak-network

networks:
  buldak-network:

volumes:
  mysql_data:
